$ErrorActionPreference = 'Continue'
Set-Location 'C:\Users\trade\mqtt-broker-rs\mio_broker'
$env:JCODE_NO_TELEMETRY = '1'
$env:DO_NOT_TRACK = '1'
$log = 'C:\Users\trade\mqtt-broker-rs\jcode_sys.log'
$args = @(
  '--provider-profile', 'zen-free',
  '--model', 'north-mini-code-free',
  '--tools', 'bash,read,write,apply_patch,grep',
  'run', 'TASK: Add MQTT broker $SYS system topics to the mio_broker Rust project. Project: C:\Users\trade\mqtt-broker-rs\mio_broker (single crate, src/main.rs is the ONLY source file). Build/verify: cd C:\Users\trade\mqtt-broker-rs\mio_broker && cargo build 2>&1 | tail -5. GOAL: Periodically publish $SYS/broker/* retained messages, Mosquitto-style (MQTT 3.1.1 spec appendix C conventions). IMPLEMENTATION (follow exactly): 1. Add counters to the Broker struct (init to 0): sys_clients_total: u64 (incremented on EVERY accepted CONNECT, including reconnects), sys_msgs_received: u64 (increment in the packet-dispatch loop for EVERY inbound packet of any type), sys_msgs_sent: u64 (increment in deliver_to / send path whenever a packet is written to a client socket), sys_pub_received: u64 (increment on inbound PUBLISH), sys_pub_sent: u64 (increment whenever a PUBLISH is delivered to a client). 2. Add field sys_start: Instant (set at broker creation) and sys_last_publish: Instant (set to sys_start initially). 3. In the main event loop timeout path, add: if sys_last_publish.elapsed() is at least 10 seconds, call publish_sys_topics() and set sys_last_publish = Instant::now(). 4. Implement publish_sys_topics(&mut self): builds retained QoS0 PUBLISH packets directly for these topics, each with retain flag set (first byte = 0x30 | 0x01): $SYS/broker/version -> value is the string mqtt-broker-rs followed by a space and the crate version via env! macro CARGO_PKG_VERSION, $SYS/broker/uptime -> seconds since sys_start, $SYS/broker/clients/connected -> current client count, $SYS/broker/clients/total -> sys_clients_total, $SYS/broker/messages/received -> sys_msgs_received, $SYS/broker/messages/sent -> sys_msgs_sent, $SYS/broker/messages/publish/received -> sys_pub_received, $SYS/broker/messages/publish/sent -> sys_pub_sent, $SYS/broker/subscriptions/count -> total subscriptions across ALL clients. Deliver each to all connected clients with matching subscription (use the SAME delivery/retained logic as normal PUBLISH path so QoS downgrade rules apply). 5. IMPORTANT: $SYS topics MUST also be stored as retained so a client subscribing to $SYS/# later receives the last values immediately. CONSTRAINTS: ONLY edit src/main.rs. Do not create new files. Keep existing behavior 100% intact (LWT, persistent sessions, QoS flows). No refactors. Additive only. No external dependencies (no chrono, no tokio). Use std::time::Instant only. After editing, run: cargo build 2>&1 | tail -5 and fix ALL errors until it compiles. Do NOT run cargo test. Report: what you changed, compile result, and any caveats. Read the relevant sections first: Broker struct, main event loop, deliver_to, retained store. Match existing style.'
)
& 'C:\Users\trade\.local\bin\jcode.exe' @args *>&1 | Out-File -FilePath $log -Encoding utf8
Write-Output "JCODE_EXIT=$LASTEXITCODE"
